l_english:
  # DELETE:
    # pm_disabled_gin
    # pm_disabled_elastics
    # pm_masticators
    # pm_rubber_bands
    # pm_luxury_clothes

  # Agriculture Buildings
 pm_primary: "Первинний"
 pmg_secondary_building_rye_farm: "Вторинний"
 pmg_secondary_building_wheat_farm: "Вторинний"
 pmg_secondary_building_rice_farm: "Вторинний"
 pmg_secondary_building_maize_farm: "Вторинний"
 pmg_secondary_building_millet_farm: "Вторинний"
 pm_no_secondary: "Однокультурність"
 pm_potatoes: "Картопля"
 pm_vineyards: "Виноградники"
 pm_vineyards_building_maize_farm: "Виноградники"
 pm_apple_orchards: "Яблуневі сади"
 pm_citrus_orchards: "Цитрусові сади"
 pm_fig_orchards: "Інжирні сади"
 pm_fig_orchards_building_rice_farm: "Інжирні сади"
 pm_mulberry_groves: "Тутові гаї"

 pmg_automation: "Самочинність"
 pmg_automation_building_food_industry: "Самочинність"
 pmg_automation_building_textile_mills:0 "Automation"
 pmg_automation_building_furniture_manufacturies: "Самочинність"
 pmg_automation_building_tooling_workshops: "Автоматізація"
 pmg_automation_building_paper_mills: "Самочинність"
 pmg_automation_building_steel_mills: "Самочинність"
 pmg_automation_building_motor_industry: "Самочинність"
 pm_civilian_priority: "Цивільний пріоритет"
 pm_military_priority: "Військовий пріоритет"

  # Textile Mills
 pm_craftsman_sewing: "Швейні майстри"
 pm_sewing_machines: "Швейні машинки"
 pm_electric_sewing_machines: "Електричні машинки"
 pm_traditional_looms: "Традиційне ткацтво"
 pm_mechanized_looms: "Механізоване ткацтво"
 pm_automatic_power_looms: "Автоматичне ткацтво"

  # Glassworks
 pm_leaded_glass: "Свинцеве скло"
 pm_manual_glassblowing: "Ручне скловидування"

  # Chemical Plants
 pm_leblanc_process: "Процес Леблана"
 pm_no_explosives_production: "Пріорітет на добрива"
 pm_ammonia-soda_process: "Сопушецько-содовий процес"
 pm_vacuum_evaporation: "Вакуумне випаровування"
 pm_brine_electrolysis: "Електроліз розсолу"
 pmg_fertilizer_production: "Виробництво добрив"
 pm_no_artificial_fertilizers: "Без штучних добрив"
 pm_artificial_fertilizers: "Штучні добрива"
 pm_improved_fertilizer: "Покращені добрива"
 pm_nitrogen_fixation: "Процес фіксації азоту"
 pm_dyes_production: "Виробництво барвників"
 pm_no_synthetic_dyes: "Без синтетичних барвників"
 pmg_synthetic_dyes: "Синтетичні барвники"
 pm_silk_production: "Виробництво шовку"
 pm_no_artificial_fibers: "Пріоритет на барвники"
 pm_rayon: "Штучний шовк"

  # Foundries
 pm_steamworks: "Парова робота"
 pm_no_artillery_production: "Стрілецька зброя"
 pm_artillery_production: "Виробництво гарматні"

  # Motor Industries
 pmg_automobile_production: "Виробництво"
 pm_automobile_production: "Виробництво автомобілів"
