l_english:
 SETTINGS_PAGE_GRAPHICS: "Графіка"
 SETTINGS_PAGE_GAME: "Гра"
 SETTINGS_PAGE_SYSTEM: "Система"
 SETTINGS_PAGE_CONTROLS: "Керування"
 SETTINGS_PAGE_EDITOR: "Редактор"
 SETTINGS_PAGE_INTERFACE: "Інтерфейс"
 SETTINGS_PAGE_AUDIO: "Звук"
 SETTINGS_CATEGORY_SCREEN: "Екран"
 SETTINGS_CATEGORY_QUALITY: "Якість"
 OPTION_EASY: "Легко"
 OPTION_NORMAL: "Нормальнo"
 OPTION_HARD: "Важко"
 OPTION_NEVER: "Ніколи"
 OPTION_MONTHLY: "Щомісяця"
 OPTION_HALFYEAR: "Щопівроку"
 OPTION_YEARLY: "Щороку"
 OPTION_FIVE_YEAR: "Кожні 5 років"
 OPTION_NO_AUTOSAVE: "Не зберігайти автоматично"
 SETTINGS_CATEGORY_ACCOUNT: "Обліковка"
 SETTINGS_CATEGORY_SYSTEM: "Система"
 SETTINGS_CATEGORY_CONTROLS: "Керування"
 SETTINGS_CATEGORY_CAMERA: "Знімач"
 SETTINGS_CATEGORY_AUDIO: "Звук"
 SETTINGS_CATEGORY_GUI: "ГІК"
 SETTINGS_CATEGORY_INPUT_BINDINGS: "Прив’язки введення"
 DISCARD: "Скасувати"
 APPLY: "Застосовувати"
 SAVE_AND_CLOSE: "Гаразд"
 SETTINGS: "Налаштування"
 REQUIRES_RESTART: "Потрібен перезапуск"
 REQUIRE_RESTART_DESCRIPTION: "Деякі налаштування не набудуть чинности, доки ви не перезапустите гру."
 SETTINGS_INPUT_REMAP_INPUT: "Переназначити введення"
 SETTINGS_INPUT_CONFIRM: "Підтвердити"
 SETTINGS_INPUT_CANCEL: "Скасувати"
 SETTINGS_INPUT_CLEAR: "Очистити"
 SETTINGS_INPUT_SAVE_INPUT_PROFILE: "Зберегти профіль"
 SETTINGS_INPUT_LOAD_INPUT_PROFILE: "Завантажити профіль"
 SETTINGS_INPUT_RESET_INPUT_PROFILE: "Скинути до значень, які були"
 SETTINGS_INPUT_BINDING_TEXT: "Виберіть прив’язку введення для дії '$INPUT_ACTION$':\n\n$INPUT_NAME$"
 SETTINGS_INPUT_BINDING_WARNING_TEXT: "Увага: Ця прив’язка введення вже існує для '$INPUT_ACTION$'!\nКлацніть '$SETTINGS_INPUT_CONFIRM$', щоб очистити стару прив'язку"
 SETTING_AUTOSAVE_TO_CLOUD: "Автозбереження в хмару"
 SETTING_SAVE_FILE_FORMAT: "Стандартний формат збереження"
 SETTING_SAVE_FILE_FORMAT_TOOLTIP: "Цей параметр замінюється в режимах залізної волі, хмарі і режим розробника"
 OPTION_SAVE_FILE_TEXT: "Текст"
 OPTION_SAVE_FILE_ZIP_TEXT_ALL: "Заархівований текст"
 OPTION_SAVE_FILE_ZIP_BINARY_ALL: "Архівований двійковий файл"
 SETTING_TOOLTIP_MODE: "Режим підказки"
 SETTING_TOOLTIP_MODE_TOOLTIP: "#T $SETTING_TOOLTIP_MODE$#!\nВиберіть спосіб блокування підказок:\n   #b Наведення мишки#! - блокує, якщо навести вказівником мишки на підказку.\n   #b Часове блокування#! - блокує підказки через певний час.\n   #b Дійове блокування#! - блокує підказки при клаці середньою кнопкою мишки.\n   #b Часове або дійове блокування#! - використовує блокування за часом або за дією"
 SETTING_TOOLTIP_MODE_NO_LOCK: "Без замка"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY: "Наведення миші"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_MOUSE_ANCHOR: "Дійове блокування ( Mouse Anchor )"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_MOUSE_ANCHOR: "Часове блокування ( Mouse Anchor )"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_WIDGET_ANCHOR: "Дійове блокування"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_WIDGET_ANCHOR: "Часове блокування"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_OR_ACTION_WIDGET_ANCHOR: "Часове або дійове блокування"
 SETTING_TOOLTIP_DELAY_TOOLTIP: "#T $SETTING_TOOLTIP_DELAY$#!\nВстановлює затримку до появи підказки під час наведення вказівника на елемент із підказкою."
 SETTING_TOOLTIP_DELAY: "Затримка перед показом"
 SETTING_TOOLTIP_UNLOCK_TIME: "Затримка розблокування"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nВстановлює затримку до розблокування підказок."
 SETTING_TOOLTIP_LOCK_TIME: "Блокування підказок"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nВстановлює затримку перед блокуванням підказок."
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED: "Заблокована затримка відкриття"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP: "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\nВстановлює затримку перед блокуванням підказок, коли інша підказка вже відкрита."
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS: "Просунуті"
 SETTINGS_CATEGORY_AUDIO_GENERAL: "Загальні"
 SETTINGS_CATEGORY_SFX: "Звукові ефекти"
 SETTINGS_CATEGORY_MFX: "Музика"
 SETTINGS_CATEGORY_LANGUAGE: "Мова"
 SETTINGS_CATEGORY_SAVE_GAMES: "Збереження гри"
 SETTINGS_CATEGORY_TOOLTIPS: "Параметри підказок"
 SETTINGS_CATEGORY_MAP_CONTROLS: "Керування мапою"
 SETTINGS_CATEGORY_MAPMODES: "Режими мапи"
 SETTING_SHADER_QUALITY: "Якість шейдерів"
 SETTING_SHADER_QUALITY_TOOLTIP: "#T $SETTING_SHADER_QUALITY$#!\nВизначає якість різних шейдерів й ефектів.\n\n#T Висока:#! Покращує якість деяких шейдерних ефектів за рахунок продуктивности.\n\n#T Середня:#! Налаштування за замовчуванням.\n\n#T Низька:#! Цей параметр призначений для компів низького клясу та не рекомендований через втрату візуальної якости. Кілька шейдерів спрощено для підвищення графічної продуктивности."
 SETTING_SHOW_NUDITY: "Показати наготу"
 SETTING_SHOW_NUDITY_TOOLTIP: "#T $SETTING_SHOW_NUDITY$#!\nВстановлює, чи можна показувати наготу."

 SETTING_VALUE_HOURS: "$VALUE|0$ Hours"
 SETTING_VALUE_HOUR_FULL: "$VALUE|0$:00"

 SETTINGS_CATEGORY_DAYNIGHT_CYCLE:0 "Day night cycle"
 SETTING_DAYNIGHT_CYCLE:0 "Enable day night cycle"
 SETTING_DAYNIGHT_CYCLE_TOOLTIP:0 "#T $SETTING_DAYNIGHT_CYCLE$#!\nEnables a day and night cycle for the sun movement."
 SETTING_DAYNIGHT_SYSTEMTIME:0 "Enable sync local time"
 SETTING_DAYNIGHT_SYSTEMTIME_TOOLTIP:0 "#T $SETTING_DAYNIGHT_SYSTEMTIME$#!\nSyncronizes the day night cycle speed and time to the computers local time.\n\n#!Will override simulation speed setting."
 SETTING_DAYNIGHT_SPEED:0 "Simulation Speed"
 SETTING_DAYNIGHT_SPEED_TOOLTIP:0 "#T $SETTING_DAYNIGHT_SPEED$#!\nHow fast the time will cycle between day and night.#"
 SETTING_SUN_DURATION:0 "Sun hours"
 SETTING_SUN_DURATION_TOOLTIP:0 "#T $SETTING_SUN_DURATION$#!\nThe amount of hours of sun in a day."
 SETTING_SUNRISE_TIME:0 "Time of sunrise"
 SETTING_SUNRISE_TIME_TOOLTIP:0 "#T $SETTING_SUNRISE_TIME$#!\nThe hour the sun will rise.\n\n#!Only used when synced with local time. #!"
 SETTING_DAYNIGHT_SET_TIME:0 "Enable manual time"
 SETTING_DAYNIGHT_SET_TIME_TOOLTIP:0 "#T $SETTING_DAYNIGHT_SET_TIME$#!\nSets time of day to a specified hour.\n\n#!Will override simulation speed and sync local time settings."
 SETTING_SUNRISE_SET_TIME_HOUR:0 "Manual time hour"
 SETTING_SUNRISE_SET_TIME_HOUR_TOOLTIP:0 "#T $SETTING_SUNRISE_SET_TIME_HOUR$#!\nLocks the time to this hour.\n\n#!Only used when manual time is enabled#"

 SETTING_BUILDINGS_CUTOFF:1 "Cull Distant Buildings"
 SETTING_BUILDINGS_CUTOFF_TOOLTIP:1 "#T $SETTING_BUILDINGS_CUTOFF$#!\nShow fewer buildings on the map, the further away they are from the camera.\n\nTurning it on may increase performance."

 SETTINGS_CATEGORY_GAME_PORTRAITS: "Портрети"
 SETTING_SOUNDTRACK: "Музика на тло"
 SETTING_SOUNDTRACK_TOOLTIP: "Загальна музика на тло"
 SETTING_MUSIC_STINGERS: "Музичні стинґери"
 SETTING_MUSIC_STINGERS_TOOLTIP: "Короткі музичні фрази для покращення ігрового процесу"

  # Audio - These are copies of clausewitz keys due to case sensitivity
 SETTING_MUSIC: "Музика"
 SETTING_AMBIENT: "Довкілля"
 SETTING_MUSIC_TOOLTIP: "#T Гучність музики\n#!Встановлює гучність музики."
 SETTING_AMBIENT_TOOLTIP: "#T Гучність довкілля\n#!Встановлює гучність довкілля."

 SETTING_MAP_TOOLTIP_DELAY: "Затримка підказки мапи"
 SETTING_MAP_TOOLTIP_DELAY_TOOLTIP: "#T $SETTING_MAP_TOOLTIP_DELAY$#!\nВстановлює затримку перед показом підказки мапи."

 SETTING_MAP_MODE_DELAY: "Затримка режиму мапи"
 SETTING_MAP_MODE_DELAY_TOOLTIP: "Затримка перед заміною новим режимом мапи старого"
 SETTING_MAP_MODE_FADE_IN: "Плавне виникнення режиму мапи"
 SETTING_MAP_MODE_FADE_IN_TOOLTIP: "Час появи нового режиму мапи після зникнення старого, у секундах"
 SETTING_MAP_MODE_FADE_OUT: "Плавне зникнення режиму мапи"
 SETTING_MAP_MODE_FADE_OUT_TOOLTIP: "Час згасання поточного режиму мапи після його затримки, коли має бути застосований новий режим мапи, у секундах"

 SETTING_OCCUPATION_STRIPES: "Смугаста окупація"
 SETTING_OCCUPATION_STRIPES_TOOLTIP: "#T $SETTING_OCCUPATION_STRIPES$#!\nУвімкнути кольорові смуги як візуальне позначення окупації на мапі замість зображень стягів країн"

 ui_skin_theme:0 "User Interface"
 ui_skin_theme_desc:0 "The buttons, frames, windows, headers, etc. in the game."
 papermap_theme:0 "Paper Map"
 papermap_theme_desc:0 "This is the map you see when you are zoomed out."
 table_top_theme:0 "Table Top"
 table_top_theme_desc:0 "If you zoom out as far as you can on the map, you can see this table on the top and bottom of your screen."
 table_asset_1_theme:0 "Table Object (top left)"
 table_asset_1_theme_desc:0 "The object displayed in the top left of the table next to the map when zoomed out."
 table_asset_2_theme:0 "Table Object (top right)"
 table_asset_2_theme_desc:0 "The object displayed in the top right of the table next to the map when zoomed out."
 table_asset_3_theme:0 "Table Object (bottom left)"
 table_asset_3_theme_desc:0 "The object displayed in the bottom left of the table next to the map when zoomed out."
 table_asset_4_theme:0 "Table Object (bottom right)"
 table_asset_4_theme_desc:0 "The object displayed in the bottom right of the table next to the map when zoomed out."
 building_sets_themes:0 "Building Set"

 color_blind_mode_test: "Тест"