l_english:
 SETTINGS_PAGE_GRAPHICS: "Графіка"
 SETTINGS_PAGE_GAME: "Гра"
 SETTINGS_PAGE_SYSTEM: "Система"
 SETTINGS_PAGE_CONTROLS: "Управління"
 SETTINGS_PAGE_EDITOR: "Редактор"
 SETTINGS_PAGE_INTERFACE: "Інтерфейс"
 SETTINGS_PAGE_AUDIO: "Авдіо"
 SETTINGS_CATEGORY_SCREEN: "Екран"
 SETTINGS_CATEGORY_QUALITY: "Якість"
 OPTION_EASY: "Легко"
 OPTION_NORMAL: "Нормальнo"
 OPTION_HARD: "Важко"
 OPTION_NEVER: "Ніколи"
 OPTION_MONTHLY: "Щомісяця"
 OPTION_HALFYEAR: "Щопівроку"
 OPTION_YEARLY: "Щороку"
 OPTION_FIVE_YEAR: "Кожні 5 років"
 OPTION_NO_AUTOSAVE: "Не зберігайти автоматично"
 SETTINGS_CATEGORY_ACCOUNT: "Обліковка"
 SETTINGS_CATEGORY_SYSTEM: "Система"
 SETTINGS_CATEGORY_CONTROLS: "Управління"
 SETTINGS_CATEGORY_CAMERA: "Знімач"
 SETTINGS_CATEGORY_AUDIO: "Авдіо"
 SETTINGS_CATEGORY_GUI: "ГІК"
 SETTINGS_CATEGORY_INPUT_BINDINGS: "Прив’язки вводу"
 DISCARD: "Скасувати"
 APPLY: "Застосовувати"
 SAVE_AND_CLOSE: "Гаразд"
 SETTINGS: "Налаштування"
 REQUIRES_RESTART: "Потрібен перезапуск"
 REQUIRE_RESTART_DESCRIPTION: "Деякі налаштування не набудуть чинности, доки ви не перезапустите гру."
 SETTINGS_INPUT_REMAP_INPUT: "Переназначити ввод"
 SETTINGS_INPUT_CONFIRM: "Підтвердити"
 SETTINGS_INPUT_CANCEL: "Скасувати"
 SETTINGS_INPUT_CLEAR: "Очистити"
 SETTINGS_INPUT_SAVE_INPUT_PROFILE: "Зберегти профіль"
 SETTINGS_INPUT_LOAD_INPUT_PROFILE: "Завантажити профіль"
 SETTINGS_INPUT_RESET_INPUT_PROFILE: "Скинути до значень за замовчуванням"
 SETTINGS_INPUT_BINDING_TEXT: "Виберіть прив’язку введення для дії '$INPUT_ACTION$':\n\n$INPUT_NAME$"
 SETTINGS_INPUT_BINDING_WARNING_TEXT: "Увага: Це прив’язування введення вже існує для '$INPUT_ACTION$'!\nКлацніть '$SETTINGS_INPUT_CONFIRM$', щоб очистити стару прив'язку"
 SETTING_AUTOSAVE_TO_CLOUD: "Автозбереження в хмару"
 SETTING_SAVE_FILE_FORMAT: "Стандартний формат збереження"
 SETTING_SAVE_FILE_FORMAT_TOOLTIP: "Цей параметр замінюється в режимах залізної волі, хмарі і режим розробника"
 OPTION_SAVE_FILE_TEXT: "Текст"
 OPTION_SAVE_FILE_ZIP_TEXT_ALL: "Заархівований текст"
 OPTION_SAVE_FILE_ZIP_BINARY_ALL: "Архівований двійковий файл"
 SETTING_TOOLTIP_MODE: "Режим підказки"
 SETTING_TOOLTIP_MODE_TOOLTIP: "#T $SETTING_TOOLTIP_MODE$#!\nВиберіть спосіб блокування підказок:\n   #b Наведення миші#! - блокує підказки, якщо навести вказівником миші на підказку.\n   #b Таймерне блокування#! - блокує підказки через встановлений час.\n   #b Дійове блокування#! - блокує підказки середньою кнопкою миші."
 SETTING_TOOLTIP_MODE_NO_LOCK: "Без замка"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY: "Наведення миші"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_MOUSE_ANCHOR: "Дійове блокування ( Mouse Anchor )"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_MOUSE_ANCHOR: "Таймерне блокування ( Mouse Anchor )"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_WIDGET_ANCHOR: "Дійове блокування"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_WIDGET_ANCHOR: "Таймерне блокування"
 SETTING_TOOLTIP_DELAY_TOOLTIP: "#T $SETTING_TOOLTIP_DELAY$#!\nВстановлює затримку до появи підказки під час наведення вказівника на елемент із підказкою."
 SETTING_TOOLTIP_DELAY: "Затримка перед показом"
 SETTING_TOOLTIP_UNLOCK_TIME: "Затримка розблокування"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nВстановлює затримку до розблокування підказок."
 SETTING_TOOLTIP_LOCK_TIME: "Блокування підказок"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nВстановлює затримку перед блокуванням підказок."
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED: "Заблокована затримка відкриття"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP: "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\nВстановлює затримку перед блокуванням підказок, коли інша підказка вже відкрита."
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS: "Просунуті"
 SETTINGS_CATEGORY_AUDIO_GENERAL: "Загальні"
 SETTINGS_CATEGORY_SFX: "Звукові ефекти"
 SETTINGS_CATEGORY_MFX: "Музика"
 SETTINGS_CATEGORY_LANGUAGE: "Мова"
 SETTINGS_CATEGORY_SAVE_GAMES: "Збереження гри"
 SETTINGS_CATEGORY_TOOLTIPS: "Параметри підказок"
 SETTINGS_CATEGORY_MAP_CONTROLS: "Керування мапою"
 SETTINGS_CATEGORY_MAPMODES: "Режими мапи"
 SETTING_SHADER_QUALITY: "Якість шейдерів"
 SETTING_SHADER_QUALITY_TOOLTIP: "#T $SETTING_SHADER_QUALITY$#!\nВизначає якість різних шейдерів й ефектів.\n\n#T Висока:#! Покращує якість деяких шейдерних ефектів за рахунок продуктивності.\n\n#T Середня:#! Налаштування за замовчуванням.\n\n#T Низька:#! Цей параметр призначений для компів низького клясу та не рекомендований через втрату візуальної якости. Кілька шейдерів спрощено для підвищення графічної продуктивности."
 SETTING_SHOW_NUDITY: "Показати наготу"
 SETTING_SHOW_NUDITY_TOOLTIP: "#T $SETTING_SHOW_NUDITY$#!\nВстановлює, чи можна показувати наготу."
 SETTINGS_CATEGORY_GAME_PORTRAITS: "Портрети"
 SETTING_SOUNDTRACK: "Фонова музика"
 SETTING_SOUNDTRACK_TOOLTIP: "Загальна фонова музика"
 SETTING_MUSIC_STINGERS: "Музичні стинґери"
 SETTING_MUSIC_STINGERS_TOOLTIP: "Короткі музичні фрази для покращення ігрового процесу"

  # Audio - These are copies of clausewitz keys due to case sensitivity
 SETTING_MUSIC: "Музика"
 SETTING_AMBIENT: "Ембієнт"
 SETTING_MUSIC_TOOLTIP: "#T Гучність музики\n#!Встановлює гучність музики."
 SETTING_AMBIENT_TOOLTIP: "#T Гучність ембієнту\n#!Встановлює гучність навколишнього середовища."

 SETTING_MAP_TOOLTIP_DELAY: "Затримка підказки мапи"
 SETTING_MAP_TOOLTIP_DELAY_TOOLTIP: "#T $SETTING_MAP_TOOLTIP_DELAY$#!\nВстановлює затримку перед показом підказки мапи."

 SETTING_MAP_MODE_DELAY: "Затримка режиму мапи"
 SETTING_MAP_MODE_DELAY_TOOLTIP: "Затримка перед заміною новим режимом мапи старого"
 SETTING_MAP_MODE_FADE_IN: "Плавне виникнення режиму мапи"
 SETTING_MAP_MODE_FADE_IN_TOOLTIP: "Час появи нового режиму мапи після зникнення старого, у секундах"
 SETTING_MAP_MODE_FADE_OUT: "Плавне зникнення режиму мапи"
 SETTING_MAP_MODE_FADE_OUT_TOOLTIP: "Час згасання поточного режиму мапи після його затримки, коли має бути застосований новий режим мапи, у секундах"

 color_blind_mode_test: "Тест"