l_english:
 SETTING_AUTOSAVE_TO_CLOUD:0 "Autosave to cloud"
 SETTING_SAVE_FILE_FORMAT:0 "Default save format"
 SETTING_SAVE_FILE_FORMAT_TOOLTIP:0 "This option is overridden in Ironman, Cloud, and Debug mode"
 OPTION_SAVE_FILE_TEXT:0 "Text"
 OPTION_SAVE_FILE_ZIP_TEXT_ALL:0 "Zipped text"
 OPTION_SAVE_FILE_ZIP_BINARY_ALL:0 "Zipped binary"
 SETTING_TOOLTIP_MODE:0 "Tooltip Mode"
 SETTING_TOOLTIP_MODE_TOOLTIP:1 "#T $SETTING_TOOLTIP_MODE$#!\nChoose how the tooltips should lock:\n   #b Mouse Tendency#! - Locks it if you move the mouse towards the tooltip.\n   #b Timer Lock#! - Locks it after a set time.\n   #b Action Lock#! - Locks it with middle mouse button."
 SETTING_TOOLTIP_MODE_NO_LOCK:0 "No lock"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY:0 "Mouse Tendency"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_MOUSE_ANCHOR:0 "Action Lock ( Mouse Anchor )"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_MOUSE_ANCHOR:0 "Timer Lock ( Mouse Anchor )"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_WIDGET_ANCHOR:0 "Action Lock"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_WIDGET_ANCHOR:0 "Timer Lock"
 SETTING_TOOLTIP_DELAY_TOOLTIP:1 "#T $SETTING_TOOLTIP_DELAY$#!\nSets the delay before the tooltip shows up when hovering an element with a tooltip."
 SETTING_TOOLTIP_DELAY:0 "Show Delay"
 SETTING_TOOLTIP_UNLOCK_TIME:0 "Unlock Delay"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP:0 "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nSets the delay before tooltips are unlocked."
 SETTING_TOOLTIP_LOCK_TIME:0 "Lock Delay"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP:0 "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nSets the delay before tooltips are locked."
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED:0 "Locked Open Delay"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP:0 "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\nSets the delay before tooltips are locked when another tooltip is already open."
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS:0 "Advanced"
 SETTINGS_CATEGORY_AUDIO_GENERAL:0 "General"
 SETTINGS_CATEGORY_SFX:1 "Sound Effects"
 SETTINGS_CATEGORY_MFX:0 "Music"
 SETTINGS_CATEGORY_LANGUAGE:0 "Language"
 SETTINGS_CATEGORY_SAVE_GAMES:0 "Save Games"
 SETTINGS_CATEGORY_TOOLTIPS:0 "Tooltip Settings"
 SETTINGS_CATEGORY_MAP_CONTROLS:0 "Map Controls"
 SETTING_SHADER_QUALITY:0 "Shader Quality"
 SETTING_SHADER_QUALITY_TOOLTIP:1 "#T Shader Quality\n#!Determines the quality of various shaders and effects.\n\n#T High:#! Improves quality of some shader effects at the cost of performance.\n\n#T Medium:#! Default setting for the intended graphical experience.\n\n#T Low:#! This setting is made for low-end machines and is not recommended due to the loss in visual quality. Multiple shaders are simplified to push graphical performance."
 SETTING_SHOW_NUDITY:0 "Show nudity"
 SETTING_SHOW_NUDITY_TOOLTIP:0 "#T $SETTING_SHOW_NUDITY$#!\nSets whether characters can be shown nude."
 SETTINGS_CATEGORY_GAME_PORTRAITS:0 "Portraits"
 SETTING_SOUNDTRACK:0 "Background Music"
 SETTING_SOUNDTRACK_TOOLTIP:0 "General background music"
 SETTING_MUSIC_STINGERS:0 "Music Stingers"
 SETTING_MUSIC_STINGERS_TOOLTIP:0 "Short musical phrases to enhance gameplay"
  # Audio - These are copies of clausewitz keys due to case sensitivity
 SETTING_MUSIC:0 "Music"
 SETTING_AMBIENT:0 "Ambient"
 SETTING_MUSIC_TOOLTIP:0 "#T Music Volume\n#!Sets the volume of the music."
 SETTING_AMBIENT_TOOLTIP:0 "#T Ambient Volume\n#!Sets the volume of environmental ambience."
 
 SETTING_MAP_TOOLTIP_DELAY:0 "Map Tooltip Delay"
 SETTING_MAP_TOOLTIP_DELAY_TOOLTIP:0 "#T $SETTING_MAP_TOOLTIP_DELAY$#!\nSets the delay before the map tooltip is shown."

 color_blind_mode_test:0 "Test"
 SETTINGS_PAGE_GRAPHICS: "$SETTINGS_PAGE_GRAPHICS_UA$"
 SETTINGS_PAGE_GAME: "$SETTINGS_PAGE_GAME_UA$"
 SETTINGS_PAGE_SYSTEM: "$SETTINGS_PAGE_SYSTEM_UA$"
 SETTINGS_PAGE_CONTROLS: "$SETTINGS_PAGE_CONTROLS_UA$"
 SETTINGS_PAGE_EDITOR: "Редактор"
 SETTINGS_PAGE_INTERFACE: "$SETTINGS_PAGE_INTERFACE_UA$"
 SETTINGS_PAGE_AUDIO: "$SETTINGS_PAGE_AUDIO_UA$"
 SETTINGS_CATEGORY_SCREEN: "$SETTINGS_CATEGORY_SCREEN_UA$"
 SETTINGS_CATEGORY_QUALITY: "$SETTINGS_CATEGORY_QUALITY_UA$"
 OPTION_EASY: "Легко"
 OPTION_NORMAL: "Нормальнo"
 OPTION_HARD: "Важко"
 OPTION_NEVER: "Ніколи"
 OPTION_MONTHLY: "Щомісяця"
 OPTION_HALFYEAR: "Щопівроку"
 OPTION_YEARLY: "Щороку"
 OPTION_FIVE_YEAR: "Кожні 5 років"
 OPTION_NO_AUTOSAVE: "Не зберігайти автоматично"
 SETTINGS_CATEGORY_ACCOUNT: "Обліковка"
 SETTINGS_CATEGORY_SYSTEM: "Система"
 SETTINGS_CATEGORY_CONTROLS: "$SETTINGS_CATEGORY_CONTROLS_UA$"
 SETTINGS_CATEGORY_CAMERA: "Знімач"
 SETTINGS_CATEGORY_AUDIO: "$SETTINGS_CATEGORY_AUDIO_UA$"
 SETTINGS_CATEGORY_GUI: "$SETTINGS_CATEGORY_GUI_UA$"
 SETTINGS_CATEGORY_INPUT_BINDINGS: "Прив’язки вводу"
 DISCARD: "Скасувати"
 SAVE_AND_CLOSE: "$SAVE_AND_CLOSE_UA$"
 SETTINGS: "$SETTINGS_UA$"
 REQUIRES_RESTART: "Потрібен перезапуск"
 REQUIRE_RESTART_DESCRIPTION: "$REQUIRE_RESTART_DESCRIPTION_UA$"
 SETTINGS_INPUT_REMAP_INPUT: "Переназначити ввод"
 SETTINGS_INPUT_CONFIRM: "Підтвердити"
 SETTINGS_INPUT_CANCEL: "Скасувати"
 SETTINGS_INPUT_CLEAR: "Очистити"
 SETTINGS_INPUT_SAVE_INPUT_PROFILE: "Зберегти профіль"
 SETTINGS_INPUT_LOAD_INPUT_PROFILE: "Завантажити профіль"
 SETTINGS_INPUT_RESET_INPUT_PROFILE: "Скинути до значень за замовчуванням"
 SETTINGS_INPUT_BINDING_TEXT: "Виберіть прив’язку введення для дії '$INPUT_ACTION$':\n\n$INPUT_NAME$"
 SETTINGS_INPUT_BINDING_WARNING_TEXT:0 "Warning: "Це прив’язування введення вже існує для '$INPUT_ACTION$'!\nPressing '$SETTINGS_INPUT_CONFIRM$' очистить стару прив'язку" #треба перевірка
 SETTING_AUTOSAVE_TO_CLOUD: "Автозбереження в хмару"
 SETTING_SAVE_FILE_FORMAT: "Стандартний формат збереження"
 SETTING_SAVE_FILE_FORMAT_TOOLTIP: "Цей параметр замінюється в режимах залізної волі, хмарі і режим розробника"
 OPTION_SAVE_FILE_TEXT: "Текст"
 OPTION_SAVE_FILE_ZIP_TEXT_ALL: "Заархівований текст"
 OPTION_SAVE_FILE_ZIP_BINARY_ALL: "Архівований двійковий файл"
 SETTING_TOOLTIP_MODE: "Режим підказки"
 SETTING_TOOLTIP_MODE_TOOLTIP: "#T $SETTING_TOOLTIP_MODE$#!\nВиберіть спосіб блокування підказок:\n   #b Наведення миші#! - Блокує підказки, якщо навести курсор миші на підказку.\n   #b Таймерне блокування#! - Блокує підказки через встановлений час.\n   #b Екшен блокування#! - Блокує підказки середньою кнопкою миші."
 SETTING_TOOLTIP_MODE_NO_LOCK: "Без замка"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY: "Наведення миші"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_MOUSE_ANCHOR: "Блокування дій ( Mouse Anchor )"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_MOUSE_ANCHOR: "Блокування таймера ( Mouse Anchor )"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_WIDGET_ANCHOR: "Блокування дій"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_WIDGET_ANCHOR: "Блокування таймера"
 SETTING_TOOLTIP_DELAY_TOOLTIP: "#T $SETTING_TOOLTIP_DELAY$#!\nВстановлює затримку до появи підказки під час наведення курсора на елемент із підказкою."
 SETTING_TOOLTIP_DELAY: "Показати затримку"
 SETTING_TOOLTIP_UNLOCK_TIME: "Затримка розблокування"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nВстановлює затримку до розблокування підказок."
 SETTING_TOOLTIP_LOCK_TIME: "Блокування підтримки"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nВстановлює затримку перед блокуванням підказок."
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED: "Заблокована затримка відкриття"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP: "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\nВстановлює затримку перед блокуванням підказок, коли інша підказка вже відкрита."
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS: "$SETTINGS_CATEGORY_ADVANCED_GRAPHICS_UA$"
 SETTINGS_CATEGORY_AUDIO_GENERAL: "$SETTINGS_CATEGORY_AUDIO_GENERAL_UA$"
 SETTINGS_CATEGORY_SFX: "$SETTINGS_CATEGORY_SFX_UA$"
 SETTINGS_CATEGORY_MFX: "$SETTINGS_CATEGORY_MFX_UA$Music"
 SETTINGS_CATEGORY_LANGUAGE: "$SETTINGS_CATEGORY_LANGUAGE_UA$"
 SETTINGS_CATEGORY_SAVE_GAMES: "$SETTINGS_CATEGORY_SAVE_GAMES_UA$"
 SETTINGS_CATEGORY_TOOLTIPS: "$SETTINGS_CATEGORY_TOOLTIPS_UA$"
 SETTINGS_CATEGORY_MAP_CONTROLS: "$SETTINGS_CATEGORY_MAP_CONTROLS_UA$"
 SETTING_SHADER_QUALITY: "$SETTING_SHADER_QUALITY_UA$"
 SETTING_SHADER_QUALITY_TOOLTIP: "#T Якість шейдерів\n#!Визначає якість різних шейдерів і ефектів.\n\n#T Висока:#! Покращує якість деяких шейдерних ефектів за рахунок продуктивності.\n\n#T Середня:#! Налаштування за замовчуванням.\n\n#T Низька:#! Цей параметр призначений для компів низького класу та не рекомендований через втрату візуальної якості. Кілька шейдерів спрощено для підвищення графічної продуктивності."
 SETTING_SHOW_NUDITY: "Показати наготу"
 SETTING_SHOW_NUDITY_TOOLTIP: "#T $SETTING_SHOW_NUDITY$#!\nВстановлює, чи можна показувати наготу."
 SETTINGS_CATEGORY_GAME_PORTRAITS: "$SETTINGS_CATEGORY_GAME_PORTRAITS_UA$"
 SETTING_SOUNDTRACK: "Фонова музика"
 SETTING_SOUNDTRACK_TOOLTIP: "Загальна фонова музика"
 SETTING_MUSIC_STINGERS: "Музичні стінґери"  #треба перевірка
 SETTING_MUSIC_STINGERS_TOOLTIP: "Короткі музичні фрази для покращення ігрового процесу"

  # Audio - These are copies of clausewitz keys due to case sensitivity
 SETTING_MUSIC: "Музика"
 SETTING_AMBIENT: "Ембієнт"
 SETTING_MUSIC_TOOLTIP: "#T Гучність музики\n#!Встановлює гучність музики."
 SETTING_AMBIENT_TOOLTIP: "#T Гучність ембієнту\n#!Встановлює гучність навколишнього середовища."
 
 SETTING_MAP_TOOLTIP_DELAY: "Затримка підказки мапи"
 SETTING_MAP_TOOLTIP_DELAY_TOOLTIP: "#T $SETTING_MAP_TOOLTIP_DELAY$#!\nВстановлює затримку перед показом підказки карти."

 color_blind_mode_test: "Тест"

 SAVE_AND_CLOSE_UA: "Гаразд"
 REQUIRE_RESTART_DESCRIPTION_UA: "Деякі налаштування не набудуть чинности, доки ви не перезапустите гру."

 SETTINGS_UA: "Налаштування"
 SETTINGS_PAGE_GRAPHICS_UA: "Графіка"
 SETTINGS_PAGE_GAME_UA: "Гра"
 SETTINGS_PAGE_SYSTEM_UA: "Система"
 SETTINGS_PAGE_CONTROLS_UA: "Управління"
 SETTINGS_PAGE_EDITOR_UA: "Редактор"
 SETTINGS_PAGE_INTERFACE_UA: "Інтерфейс"
 SETTINGS_PAGE_AUDIO_UA: "Авдіо"
 SETTINGS_CATEGORY_SCREEN_UA: "Екран"
 SETTINGS_CATEGORY_QUALITY_UA: "Якість"
 SETTINGS_CATEGORY_AUDIO_UA: "Авдіо"
 SETTINGS_CATEGORY_GUI_UA: "ГІК"
 SETTINGS_CATEGORY_CONTROLS_UA: "Управління"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS_UA: "Просунуті"
 SETTINGS_CATEGORY_AUDIO_GENERAL_UA: "Загальні"
 SETTINGS_CATEGORY_SFX_UA: "Звукові ефекти"
 SETTINGS_CATEGORY_MFX_UA: "Музика"
 SETTINGS_CATEGORY_LANGUAGE_UA: "Мова"
 SETTINGS_CATEGORY_SAVE_GAMES_UA: "Збереження гри"
 SETTINGS_CATEGORY_TOOLTIPS_UA: "Параметри підказок"
 SETTINGS_CATEGORY_MAP_CONTROLS_UA: "Керування мапою"
 SETTINGS_CATEGORY_GAME_PORTRAITS_UA: "Портрети"

 SETTING_SHADER_QUALITY_UA: "Якість шейдерів"