l_russian:
 SETTINGS_PAGE_GRAPHICS: " Графіка"
 SETTINGS_PAGE_GAME: " Гра"
 SETTINGS_PAGE_SYSTEM: " Система"
 SETTINGS_PAGE_CONTROLS: " Управління"
 SETTINGS_PAGE_EDITOR:0 "Editor"
 SETTINGS_PAGE_INTERFACE: " Інтерфейс"
 SETTINGS_PAGE_AUDIO: " Авдіо"
 SETTINGS_CATEGORY_SCREEN: " Екран"
 SETTINGS_CATEGORY_QUALITY: " Якість"
 OPTION_EASY: "Легко"
 OPTION_NORMAL: "Нормальнo"
 OPTION_HARD: "Важко"
 OPTION_NEVER: "Ніколи"
 OPTION_MONTHLY: "Щомісяця"
 OPTION_HALFYEAR: "Щопівроку"
 OPTION_YEARLY: "Щороку"
 OPTION_FIVE_YEAR: "Кожні 5 років"
 OPTION_NO_AUTOSAVE: "Не зберігайти автоматично"
 SETTINGS_CATEGORY_ACCOUNT:0 "Account"
 SETTINGS_CATEGORY_SYSTEM:0 "System"
 SETTINGS_CATEGORY_CONTROLS: " Управління"
 SETTINGS_CATEGORY_CAMERA:0 "Camera"
 SETTINGS_CATEGORY_AUDIO: " Авдіо"
 SETTINGS_CATEGORY_GUI: "ГІК"
 SETTINGS_CATEGORY_INPUT_BINDINGS:0 "Input Bindings"
 DISCARD:0 "Discard"
 SAVE_AND_CLOSE: "Гаразд"
 SETTINGS: "Налаштування"
 REQUIRES_RESTART: "Потрібен перезапуск"
 REQUIRE_RESTART_DESCRIPTION:0 "Some settings will not take effect until you restart the game."
 SETTINGS_INPUT_REMAP_INPUT:0 "Remap input"
 SETTINGS_INPUT_CONFIRM: "Підтвердити"
 SETTINGS_INPUT_CANCEL: "Скасувати"
 SETTINGS_INPUT_CLEAR:0 "Clear"
 SETTINGS_INPUT_SAVE_INPUT_PROFILE:0 "Save Profile"
 SETTINGS_INPUT_LOAD_INPUT_PROFILE:0 "Load Profile"
 SETTINGS_INPUT_RESET_INPUT_PROFILE:0 "Reset to Defaults"
 SETTINGS_INPUT_BINDING_TEXT:0 "Please choose an input binding for the action '$INPUT_ACTION$':\n\n$INPUT_NAME$"
 SETTINGS_INPUT_BINDING_WARNING_TEXT:0 "Warning: This input binding already exists for '$INPUT_ACTION$'!\nPressing '$SETTINGS_INPUT_CONFIRM$' will clear the old binding"
 SETTING_AUTOSAVE_TO_CLOUD: "Автозбереження в хмару"
 SETTING_SAVE_FILE_FORMAT: "Стандартний формат збереження"
 SETTING_SAVE_FILE_FORMAT_TOOLTIP: "Цей параметр замінюється в режимах Ironman, Cloud і Debug_mode"
 OPTION_SAVE_FILE_TEXT:0 "Text"
 OPTION_SAVE_FILE_ZIP_TEXT_ALL:0 "Zipped text"
 OPTION_SAVE_FILE_ZIP_BINARY_ALL:0 "Zipped binary"
 SETTING_TOOLTIP_MODE:0 "Tooltip Mode"
 SETTING_TOOLTIP_MODE_TOOLTIP:1 "#T $SETTING_TOOLTIP_MODE$#!\nChoose how the tooltips should lock:\n   #b Mouse Tendency#! - Locks it if you move the mouse towards the tooltip.\n   #b Timer Lock#! - Locks it after a set time.\n   #b Action Lock#! - Locks it with middle mouse button."
 SETTING_TOOLTIP_MODE_NO_LOCK:0 "No lock"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY:0 "Mouse Tendency"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_MOUSE_ANCHOR:0 "Action Lock ( Mouse Anchor )"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_MOUSE_ANCHOR:0 "Timer Lock ( Mouse Anchor )"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_WIDGET_ANCHOR:0 "Action Lock"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_WIDGET_ANCHOR:0 "Timer Lock"
 SETTING_TOOLTIP_DELAY_TOOLTIP:1 "#T $SETTING_TOOLTIP_DELAY$#!\nSets the delay before the tooltip shows up when hovering an element with a tooltip."
 SETTING_TOOLTIP_DELAY:0 "Show Delay"
 SETTING_TOOLTIP_UNLOCK_TIME:0 "Unlock Delay"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP:0 "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nSets the delay before tooltips are unlocked."
 SETTING_TOOLTIP_LOCK_TIME:0 "Lock Delay"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP:0 "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nSets the delay before tooltips are locked."
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED:0 "Locked Open Delay"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP:0 "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\nSets the delay before tooltips are locked when another tooltip is already open."
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS: " Просунуті"
 SETTINGS_CATEGORY_AUDIO_GENERAL: " Загальні"
 SETTINGS_CATEGORY_SFX: " Спеціяльні звукові ефекти"
 SETTINGS_CATEGORY_LANGUAGE: " Мова"
 SETTINGS_CATEGORY_SAVE_GAMES: " Збереження гри"
 SETTINGS_CATEGORY_TOOLTIPS: " Параметри підказок"
 SETTINGS_CATEGORY_MAP_CONTROLS: " Керування мапою"
 SETTING_SHADER_QUALITY: "Якість шейдерів"
 SETTING_SHADER_QUALITY_TOOLTIP:1 "#T Shader Quality\n#!Determines the quality of various shaders and effects.\n\n#T High:#! Improves quality of some shader effects at the cost of performance.\n\n#T Medium:#! Default setting for the intended graphical experience.\n\n#T Low:#! This setting is made for low-end machines and is not recommended due to the loss in visual quality. Multiple shaders are simplified to push graphical performance."
 SETTING_SHOW_NUDITY:0 "Show nudity"
 SETTING_SHOW_NUDITY_TOOLTIP:0 "#T $SETTING_SHOW_NUDITY$#!\nSets whether characters can be shown nude."
 SETTINGS_CATEGORY_GAME_PORTRAITS: "Портрети"
  # Audio - These are copies of clausewitz keys due to case sensitivity
 SETTING_MUSIC: "Музика"
 SETTING_AMBIENT: "Ембієнт"
 SETTING_MUSIC_TOOLTIP:0 "#T Music Volume\n#!Sets the volume of the music."
 SETTING_AMBIENT_TOOLTIP:0 "#T Ambient Volume\n#!Sets the volume of environmental ambience."

 color_blind_mode_test:0 "Test"
