l_russian:
  # Agriculture Buildings
 pm_primary:0 "Primary"
 pmg_secondary_building_rye_farm:0 "Secondary"
 pmg_secondary_building_wheat_farm:0 "Secondary"
 pmg_secondary_building_rice_farm:0 "Secondary"
 pmg_secondary_building_maize_farm:0 "Secondary"
 pmg_secondary_building_millet_farm:0 "Secondary"
 pm_no_secondary:0 "Maintain Single Crop"
 pm_potatoes:0 "Potatoes"
 pm_vineyards:0 "Vineyards"
 pm_vineyards_building_maize_farm:0 "Vineyards"
 pm_apple_orchards:0 "Apple Orchards"
 pm_citrus_orchards:0 "Citrus Orchards"
 pm_fig_orchards:0 "Fig Orchards"
 pm_mulberry_groves:0 "Mulberry Groves"

 pmg_automation:0 "Автоматизація"
 pmg_automation_building_food_industry:0 "Автоматизація"
 
 pm_civilian_priority:0 "Civilian Priority"
 pm_military_priority:0 "Military Priority"

  # Chemical Plants
 pm_leblanc_process:0 "Leblanc Process"
 pm_no_explosives_production:0 "Prioritize Fertilizer Production"
 pm_ammonia-soda_process:0 "Ammonia-soda Process"
 pm_vacuum_evaporation:0 "Vacuum Evaporation"
 pm_brine_electrolysis:0 "Brine Electrolysis"
 pmg_fertilizer_production:0 "Fertilizer Production"
 pm_no_artificial_fertilizers:0 "No Artificial Fertilizers"
 pm_artificial_fertilizers:0 "Artificial Fertilizers"
 pm_improved_fertilizer:0 "Improved Fertilizers"
 pm_nitrogen_fixation:0 "Nitrogen Fixation Process"
 pm_dyes_production:0 "Dyes Production"
 pm_no_synthetic_dyes:0 "No Synthetic Dyes"
 pmg_synthetic_dyes:0 "Synthetic Dyes"
 pm_silk_production:0 "Silk Production"
 pm_no_artificial_fibers:0 "Prioritize Dye Production"
 pm_rayon:0 "Rayon"

  # Foundries
 pm_steamworks:0 "Steamworks"
 