l_english:
 # General 
 SETTING_VALUE_NONE: "$VALUE$"
 SETTING_VALUE_TOTAL_PERCENTAGE: "$VALUE|%/0$"
 SETTING_VALUE_PERCENTAGE: "$VALUE|%0$"
 SETTING_VALUE_SECONDS: "$VALUE$ секунд"
 SETTING_VALUE_MINUTES: "$VALUE$ хвилин"
 # Graphics
 SETTING_RENDERER: "Рендерер"
 SETTING_VSYNC: "VSync"
 SETTING_VSYNC_TOOLTIP: "#T $SETTING_VSYNC$\n#!Робить у грі та вашому моніторі однакову частоту кадрів, зменшуючи розриви екрана.\n\nВимкнення може збільшити продуктивність."
 SETTING_PORTRAIT_MULTI_SAMPLING: "Портретне багаторазове згладжування"
 SETTING_PORTRAIT_MULTI_SAMPLING_TOOLTIP: "#T $SETTING_PORTRAIT_MULTI_SAMPLING$\n#!Використання кількох зразків для Alpha-To-Coverage для більш гладкого відображення волосся.\n\nНижчі налаштування підвищують продуктивність."
 SETTING_MULTI_SAMPLING: "Згладжування (MSAA)"
 SETTING_MULTI_SAMPLING_TOOLTIP: "#T $SETTING_MULTI_SAMPLING$\n#!Використання багаторазового згладжування (MSAA) зробить краї зображень більш гладкими.\n\nНижчі налаштування можуть збільшити продуктивність."
 SETTING_ANTI_ALIASING: "Згладжування"
 SETTING_ANTI_ALIASING_TOOLTIP: "#T $SETTING_ANTI_ALIASING$\n#!Використання згладжування зробить краї зображень більш гладкими.\n\nFXAA рекомендується."
 OPTION_ANTI_ALIASING_DISABLED: "Вимкнено"
 OPTION_ANTI_ALIASING_FXAA: "FXAA"
 SETTING_ANISOTROPIC_FILTERING: "Фільтрація текстур"
 SETTING_ANISOTROPIC_FILTERING_TOOLTIP: "#T $SETTING_ANISOTROPIC_FILTERING$\n#!Використання анізотропної фільтрації покращить вигляд текстур.\n\nНижчі налаштування можуть збільшити продуктивність."
 SETTING_FULLSCREEN_RESOLUTION: "Роздільна здатність"
 SETTING_FULLSCREEN_RESOLUTION_TOOLTIP: "#T $SETTING_FULLSCREEN_RESOLUTION$\n#!Встановлює якість зображення гри.\n\nНижча роздільна здатність може збільшити продуктивність.\n\n#X Роздільна здатність гри з непідтримуваним співвідношенням сторін може призвести до того, що інтерфейси відображатимуться поза екраном#!"
 SETTING_WINDOWED_RESOLUTION: "Віконна роздільна здатність"
 SETTING_WINDOWED_RESOLUTION_TOOLTIP: "#T $SETTING_WINDOWED_RESOLUTION$\n#!Встановлює роздільну здатність вікна гри, якщо гра знаходиться у віконному режимі.\n\nМає бути у форматі #b NUMBER#!x#b NUMBER#!.\n\n#X Роздільна здатність гри з непідтримуваним співвідношенням сторін може призвести до того, що інтерфейси відображатимуться поза екраном#!"
 SETTING_RENDER_SCALE: "Масштаб візуалізації"
 SETTING_RENDER_SCALE_TOOLTIP: "#T $SETTING_RENDER_SCALE$#!\nМасштаб роздільної здатності рендерингу гри відносно основної роздільної здатності, за винятком інтерфейсу користувача.\n\nНижчі налаштування можуть збільшити продуктивність але зменшить загальну точність, тоді як перевищення на 100% може підвищити точність, але ймовірно погіршить продуктивність."
 SETTING_RENDER_SCALE_FORMAT:0 "$VALUE|%0$"
 SETTING_DISPLAY: "Монітор"
 SETTING_DISPLAY_TOOLTIP: "#T $SETTING_DISPLAY$\n#!Якщо ваш комп’ютер має кілька моніторів, виберіть той, який використовуватиме гра."
 SETTING_GRAPHICS_DEVICE: "Відевокарта"
 SETTING_GRAPHICS_DEVICE_TOOLTIP: "#T $SETTING_GRAPHICS_DEVICE$\n#!Вибирає, яку відевокарту використовуватиме гра. \n\nВикористання вбудованої відевокарти або програмного рендерера може знизити продуктивність."
 SETTING_SHADOW_MAP_RESOLUTION: "Якість тіней"
 SETTING_SHADOW_MAP_RESOLUTION_TOOLTIP: "#T $SETTING_SHADOW_MAP_RESOLUTION$\n#!Визначає роздільну здатність візуалізації карт тіней, якщо тіні ввімкнено.\n\nНижчі налаштування можуть збільшити продуктивність."
 SETTING_DISPLAY_MODE: "Режим відображення"
 SETTING_DISPLAY_MODE_TOOLTIP: "#T $SETTING_DISPLAY_MODE$\n#!Визначає спосіб відображення гри на екрані"
 SETTING_BLOOM: "Блюм"
 SETTING_MESH_LOD_BIAS: "Якість Mesh LOD"
 SETTING_MESH_LOD_FADE: "Сітка LOD Fade"
 SETTING_TERRAIN_SMOOTHING: "Згладжування рельєфу"
 OPTION_FULLSCREEN: "Повноекранний"
 OPTION_FULLSCREEN_TOOLTIP: "#T $OPTION_FULLSCREEN$\n#!Показати гру на весь екран. Налаштування роздільної здатності змінює чіткість зображення."
 OPTION_WINDOWED: "Вікно"
 OPTION_WINDOWED_TOOLTIP: "#T $OPTION_WINDOWED$\n#!Display the game in a window. The Resolution setting changes the size of the window."
 OPTION_DISABLED: "Вимкнено"
 OPTION_OFF: "Вимкнено"
 OPTION_LOW: "Низький"
 OPTION_MEDIUM: "Середні"
 OPTION_HIGH: "Високі"
 OPTION_ULTRA: "Ультра"
 OPTION_CUSTOM: "Користувальницькі"
 OPTION_DEFAULT: "За замовчуванням"
 SETTINGS_CATEGORY_UI: "Інтерфейс"
 SETTINGS_CATEGORY_GAME: "Гра"
 SETTING_TEXTURE_QUALITY: "Якість текстур"
 SETTING_TEXTURE_QUALITY_TOOLTIP: "#T $SETTING_TEXTURE_QUALITY$#!\nКерує роздільною здатністю завантажених текстур.\n\nНижчі налаштування можуть збільшити продуктивність."
 SETTING_QUALITY: "Попереднє налаштування якости"
 SETTING_SFX: "SFX"
 SETTING_UI: "Інтерфейс"
 SETTING_QUALITY_TOOLTIP: "#T $SETTING_QUALITY$\n#!Виберіть попереднє налаштування розширених параметрів графіки нижче.\n\nНизьке налаштування підвищить продуктивність."
 SETTING_BLOOM_TOOLTIP: "#T $SETTING_BLOOM$\n#!Вмикає блюм ефект, де надзвичайно яскраве світло переливатиметься на інші частини зображення.\n\nВимкнення може збільшити продуктивність."
 SETTING_DOF_TOOLTIP: "#T $SETTING_DOF$\n#!Вмикає глибину різкості для імітації об’єктива камери, розмиває точки зображення поза фокусом.\n\nВимкнення може збільшити продуктивність."
 SETTING_LENS_FLARE_TOOLTIP: "#T $SETTING_LENS_FLARE$\n#!Enables a lens flare effect which appears in highly blooming areas. Bloom must be enabled for the effect to appear. \n\nВимкнення може збільшити продуктивність."
 SETTING_MAP_SSAO_TOOLTIP: "#T $SETTING_MAP_SSAO$\n#!Визначає, чи слід застосувати до мапи зовнішню оклюзію екранного простору.\n\nВимкнення може збільшити продуктивність."
 SETTING_REFRACTION_TOOLTIP: "Визначає, чи з'являються заломлення на воді чи ні."
 SETTING_REFRACTION_QUALITY_TOOLTIP: "#T $SETTING_REFRACTION_QUALITY$#!\nКонтролює якість заломлення води, якщо вони включені.\n\nНижчі налаштування можуть збільшити продуктивність."
 SETTING_MAPOBJECT_QUALITY_TOOLTIP: "#T $SETTING_MAPOBJECT_QUALITY$#!\nВизначає найвищий рівень якости об’єктів мапи (наприклад, будівель).\n\nНижчі налаштування можуть збільшити продуктивність."
 SETTING_MESH_LOD_BIAS_TOOLTIP: "#T $SETTING_MESH_LOD_BIAS$#!\nВизначає якість LOD (рівнів деталізації) на об’єктах мапи, таких як моделі одиниць.\n\nНижчі налаштування можуть збільшити продуктивність."
 SETTING_MESH_LOD_FADE_TOOLTIP: "#T $SETTING_MESH_LOD_FADE$\n#!Якщо ввімкнено, 3D-моделі плавно переходять між різними рівнями деталізації (LOD), коли ви збільшуєте чи зменшуєте масштаб.\n\nВимкнення може збільшити продуктивність."
 SETTING_PROVINCE_NAMES_TOOLTIP: "Визначає, як назви міст і провінцій відображаються на карті."
 SETTING_FILL_IN_IMPASSABLE_TERRAIN_TOOLTIP: "Визначає, чи входить непрохідна місцевість до кордонів країни на карті."
 SETTING_LANGUAGE_TOOLTIP: "#T $SETTING_LANGUAGE$#!\nВизначає мову інтерфейсу користувача."
 SETTING_ACCOUNT_EMAIL_TOOLTIP: "Ваша електронна адреса облікового запису Paradox"
 SETTING_FRAMERATE_CAP: "Максимальний FPS"
 SETTING_FRAMERATE_CAP_TOOLTIP: "#T $SETTING_FRAMERATE_CAP$#!\nМаксимальна кількість кадрів в секунду (FPS), яку візуалізує гра.\n\nНижчі налаштування можуть зменшити споживання електроенергії."
 OPTION_CAP_30: "30"
 OPTION_CAP_60: "60"
 OPTION_CAP_90: "90"
 OPTION_CAP_120: "120"
 OPTION_CAP_144: "144"
 OPTION_CAP_165: "165"
 SETTING_TEXTURE_STREAMING: "Потокове передавання текстур"
 SETTING_TEXTURE_STREAMING_CACHE: "Розмір кешу потокової передачі текстур"
 SETTING_VALUE_MB: "$VALUE$ Мб"
 # GUI
 SETTING_ANIMATION_SPEED: "Швидкість анімації"
 SETTING_GUI_SCALING: "Масштабування GUI"
 SETTING_GUI_SCALING_TOOLTIP: "#T $SETTING_GUI_SCALING$\n#!Встановлює масштаб усього інтерфейсу користувача. Корисно для вищої роздільної здатності екрана.\n\n#X Якщо встановити занадто високе значення, інтерфейси не будуть належним чином розміщуватися на екрані!#!"
 # System
 SETTING_SCREEN_EDGE_SCROLL_MODE: "Панорамування миші"
 SETTING_SCREEN_EDGE_SCROLL_MODE_FREE: "Безкоштовно"
 SETTING_SCREEN_EDGE_SCROLL_MODE_8_DIRECTIONS: "8 напрямків"
 SETTING_SCREEN_EDGE_SCROLL_DISABLED: "Вимкнено"
 SETTING_SCREEN_EDGE_SCROLL_MODE_TOOLTIP: "#T $SETTING_SCREEN_EDGE_SCROLL_MODE$#!\nЯк поводиться камера під час панорамування за допомогою миші."
 SETTING_SCROLL_SPEED: "Швидкість панорамування"
 SETTING_SCROLL_SPEED_TOOLTIP: "#T $SETTING_SCROLL_SPEED$#!\nВстановлює швидкість переміщення мапи при використання клавіятури чи миші."
 SETTING_CAMERA_ROTATION_SPEED: "Швидкість обертання камери"
 SETTING_CAMERA_ROTATION_SPEED_TOOLTIP: "#T $SETTING_CAMERA_ROTATION_SPEED$#!\nШвидкість обертання камери."
 SETTING_ZOOM_SPEED: "Швидкість масштабування"
 SETTING_ZOOM_SPEED_TOOLTIP: "#T $SETTING_ZOOM_SPEED$#!\nШвидкість збільшення камери."
 SETTING_MOUSE_CURSOR_ZOOM_MODE: "Поведінка масштабування"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_RELATIVE_CURSOR: "Відносний курсор"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_ZOOM_IN_TO_CURSOR: "Збільшити курсор"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_IGNORE_CURSOR: "Ігнорувати курсор"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_TOOLTIP: "#T $SETTING_MOUSE_CURSOR_ZOOM_MODE$#!\nЯк камера поводиться відносно курсора миші під час збільшення/зменшення."
 SETTING_INPUT_DEVICE: "Пристрій введення"
 SETTING_EDITOR:0 "Editor"
 SETTING_EDITOR_POSTFIX:0 "Editor postfix"
 SETTING_EDITOR_OPEN_FILE_FORMAT:0 "Editor open command"
 SETTING_LOG_VIEWER_OPEN_FILE_FORMAT:0 "View log command"
 SETTING_CODE_EDITOR_OPEN_FILE_FORMAT:0 "Code editor open command"
 SETTING_GRACEFUL_EXIT: "Витончений вихід"
 SETTING_LANGUAGE: "Мова"
 MOUSE_AND_KEYBOARD: "Мишка і клавіятура"
 GAMEPAD: "Геймпад"
 SETTING_MULTISAMPLING_DISABLED: "Вимкнено"
 SETTING_PORTRAIT_MULTISAMPLING_DISABLED: "Вимкнено"
 SETTING_ANISOTROPIC_FILTERING_DISABLED: "Вимкнено"
 # Editor
 SETTING_CAMERA_TILT:0 "Camera tilt"
 SETTING_CAMERA_STRATEGY:0 "Camera type"
 SETTING_CENTERED_ZOOM_IN:0 "Centered zoom-in"
 SETTING_CAMERA_SPEED:0 "Camera speed"
 CAMERA_TABLETOP:0 "Table top"
 CAMERA_FPS:0 "First person"
 CAMERA_WASD:0 "WASD-style"
 # Audio
 SETTING_Music: "Музика"
 SETTING_Ambient: "Ембієнт"
 SETTING_Effects: "Ефекти"
 SETTING_Master: "Майстер"
 SETTING_Master_TOOLTIP: "#T Майстер гучність\n#!Встановлює гучність усіх звуків у грі."
 SETTING_Music_TOOLTIP: "#T Гучність музики\n#!Встановлює гучність музики."
 SETTING_Ambient_TOOLTIP: "#T Гучність ембієнту\n#!Встановлює гучність навколишнього середовища."
 SETTING_SFX_TOOLTIP: "#T SFX гучність\n#!Встановлює гучність звукових ефектів, наприклад бою."
 SETTING_UI_TOOLTIP: "#T Гучність інтерфейсу\n#!Встановлює гучність інтерфейсу користувача."
 SETTING_AUDIO_DEBUG_LOG_LEVEL: "Рівень журналу налагодження"
 SETTING_AUDIO_DEVICE_PROFILE: "Аудіо профіль"
 SETTING_AUDIO_DEVICE_PROFILE_TOOLTIP: "#T $SETTING_AUDIO_DEVICE_PROFILE$\n#!Виберіть профіль аудіо, який відповідає вашим налаштуванням."
 SETTING_AUDIO_OPTION_SPEAKERS: "Колонки"
 SETTING_AUDIO_OPTION_SPEAKERS_TOOLTIP: "#T $SETTING_AUDIO_OPTION_SPEAKERS$\n#!Стандартний мікс для $SETTING_AUDIO_OPTION_SPEAKERS$."
 SETTING_AUDIO_OPTION_HEADPHONES: "Навушники"
 SETTING_AUDIO_OPTION_HEADPHONES_TOOLTIP: "#T $SETTING_AUDIO_OPTION_HEADPHONES$\n#!Мікс з поправкою на $SETTING_AUDIO_OPTION_HEADPHONES$."
 SETTING_AUDIO_OPTION_TV: "ТБ"
 SETTING_AUDIO_OPTION_TV_TOOLTIP: "#T $SETTING_AUDIO_OPTION_TV$\n#!Мікс для $SETTING_AUDIO_OPTION_TV$ і моніторних колонок."
 SETTING_AUDIO_OPTION_NIGHTMODE: "Нічний режим"
 SETTING_AUDIO_OPTION_NIGHTMODE_TOOLTIP: "#T $SETTING_AUDIO_OPTION_NIGHTMODE$\n#!Пом’якшує звук для нічної гри, приглушуючи вищі тони та стискаючи динамічний діяпазон."
 # Game
 SETTING_AUTOSAVE: "Інтервал автозбереження"
 SETTING_AUTOSAVE_TOOLTIP: "#T $SETTING_AUTOSAVE$\n#!Встановлює частоту автоматичного збереження гри."
 SETTING_AUTOSAVE_TO_CLOUD_TOOLTIP: "Визначає, чи зберігаються автозбереження в хмарі."
 SETTING_CAMERA_FACE_NORTH_TOOLTIP: "Визначає, чи буде камера завжди спрямована на північ чи ні."
 NO_AUTOSAVE: "Без автозбереження"
 # Multiplayer
 SETTINGS_FILE_TRANSFER_SPEED: "Швидкість передачі файлів"
 SETTINGS_FILE_TRANSFER_SPEED_TOOLTIP: "#T $File Transfer Speed$\n#!Встановлює максимальну швидкість передачі файлів збереження гри в лобі для кількох гравців.\n\nНижчі параметри можуть покращити стабільність мережі під час приєднання до багатокористувацьких ігор, але негативно впливають на час завантаження багатокористувацьких ігор."
 # Tools
 SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES: "Автоматичне збереження редактора карт (хвилини)"
 SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES_TOOLTIP: "Інтервал автоматичного збереження редактора карт (хвилини)"
 SETTING_NODE_EDITOR_DRAG_PAN_MODE: "Режим перетягування редактора вузлів"
 # Accessibility
 SETTINGS_CATEGORY_ACCESSIBILITY: "Доступність"
 SETTING_COLOR_BLIND_MODE: "Режим дальтоніка"
 SETTING_COLOR_BLIND_MODE_TOOLTIP: "#T $SETTING_COLOR_BLIND_MODE$\n#!Змінює кольори, які використовуються в тексті протягом гри, на набір кольорів, який легше розрізняти для різних типів дальтонізму."
