l_english:
 SETTINGS_PAGE_GRAPHICS: "Графіка"
 SETTINGS_PAGE_GAME: "Гра"
 SETTINGS_PAGE_SYSTEM: "Система"
 SETTINGS_PAGE_CONTROLS: "Керування"
 SETTINGS_PAGE_EDITOR: "Редактор"
 SETTINGS_PAGE_INTERFACE: "Інтерфейс"
 SETTINGS_PAGE_AUDIO: "Звук"
 SETTINGS_CATEGORY_SCREEN: "Екран"
 SETTINGS_CATEGORY_QUALITY: "Якість"
 OPTION_EASY: "Легко"
 OPTION_NORMAL: "Нормальнo"
 OPTION_HARD: "Важко"
 OPTION_NEVER: "Ніколи"
 OPTION_MONTHLY: "Щомісяця"
 OPTION_HALFYEAR: "Щопівроку"
 OPTION_YEARLY: "Щороку"
 OPTION_FIVE_YEAR: "Кожні 5 років"
 OPTION_NO_AUTOSAVE: "Не зберігайти автоматично"
 SETTINGS_CATEGORY_ACCOUNT: "Обліковка"
 SETTINGS_CATEGORY_SYSTEM: "Система"
 SETTINGS_CATEGORY_CONTROLS: "Керування"
 SETTINGS_CATEGORY_CAMERA: "Знімач"
 SETTINGS_CATEGORY_AUDIO: "Звук"
 SETTINGS_CATEGORY_GUI: "ГІК"
 SETTINGS_CATEGORY_INPUT_BINDINGS: "Прив’язки введення"
 DISCARD: "Скасувати"
 APPLY: "Застосовувати"
 SAVE_AND_CLOSE: "Гаразд"
 SETTINGS: "Налаштування"
 REQUIRES_RESTART: "Потрібен перезапуск"
 REQUIRE_RESTART_DESCRIPTION: "Деякі налаштування не набудуть чинности, доки ви не перезапустите гру."
 SETTINGS_INPUT_REMAP_INPUT: "Переназначити введення"
 SETTINGS_INPUT_CONFIRM: "Підтвердити"
 SETTINGS_INPUT_CANCEL: "Скасувати"
 SETTINGS_INPUT_CLEAR: "Очистити"
 SETTINGS_INPUT_SAVE_INPUT_PROFILE: "Зберегти профіль"
 SETTINGS_INPUT_LOAD_INPUT_PROFILE: "Завантажити профіль"
 SETTINGS_INPUT_RESET_INPUT_PROFILE: "Скинути до значень, які були"
 SETTINGS_INPUT_BINDING_TEXT: "Виберіть прив’язку введення для дії '$INPUT_ACTION$':\n\n$INPUT_NAME$"
 SETTINGS_INPUT_BINDING_WARNING_TEXT: "Увага: Ця прив’язка введення вже існує для '$INPUT_ACTION$'!\nКлацніть '$SETTINGS_INPUT_CONFIRM$', щоб очистити стару прив'язку"
 SETTINGS_INPUT_BINDING_MODIFIERS_WARNING_TEXT: "Увага: input binding can not consist of only modifier keys"


