l_english:
 SETTING_REFRACTION: "Заломлення"
 SETTING_REFRACTION_QUALITY: "Якість заломлення"
 SETTING_MAPOBJECT_QUALITY: "Об'єкти карти"
 SETTING_MAP_SSAO: "Карта SSAO"
 SETTING_DOF: "Глибина різкості"
 SETTING_LENS_FLARE: "Відблиск об'єктива"